services:
  elasticsearch:
    # Elasticsearch service for local development
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node  # No clustering
      - bootstrap.memory_lock=true  # Avoid swapping
      - xpack.security.enabled=false  # Disable security for local dev
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # JVM heap size
    ulimits:
      memlock:
        soft: -1
        hard: -1  # Prevent memory swapping
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Elasticsearch HTTP API
    networks:
      - elastic

  kibana:
    # Kibana UI for Elasticsearch
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    ports:
      - "5601:5601"  # Kibana Web UI
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elastic

  keycloak:
    image: quay.io/keycloak/keycloak:23.0 #Keycloak version 23.0 from offical Quay repo.
    ports:
      - "9090:8080" # Expose container port 8080 on host port 9090
    environment:
      KEYCLOAK_ADMIN: admin # Default admin username.
      KEYCLOAK_ADMIN_PASSWORD: admin # Default admin password (change in prod).
      KC_DB: h2-file # Use H2 file based dev database (not going to be used in prod).
    volumes:
      - keycloak-data:/opt/keycloak/data # Persist H2 database and config.
    command:
      - start-dev # Start keycloak in dev mode (disables HTTPs, enables bug tools).
      - --db=dev-file # Set dev DB mode 

volumes:
  elasticsearch-data:
    driver: local

networks:
  elastic:
    driver: bridge